export const USER_GET_REQUEST = 'USER_GET_REQUEST'
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS'
export const USER_GET_FAILURE = 'USER_GET_FAILURE'

export const USER_PROFILE_PUBLIC_UPDATE_REQUEST = 'USER_PROFILE_PUBLIC_UPDATE_REQUEST'
export const USER_PROFILE_PUBLIC_UPDATE_SUCCESS = 'USER_PROFILE_PUBLIC_UPDATE_SUCCESS'
export const USER_PROFILE_PUBLIC_UPDATE_FAILURE = 'USER_PROFILE_PUBLIC_UPDATE_FAILURE'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAILURE = 'USER_PROFILE_UPDATE_FAILURE'

export const USERS_GET_REQUEST = 'USERS_GET_REQUEST'
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS'
export const USERS_GET_FAILURE = 'USERS_GET_FAILURE'

export const USER_PROFILE_GET_ALL_REQUEST = 'USER_PROFILE_GET_ALL_REQUEST'
export const USER_PROFILE_GET_ALL_SUCCESS = 'USER_PROFILE_GET_ALL_SUCCESS'
export const USER_PROFILE_GET_ALL_FAILURE = 'USER_PROFILE_GET_ALL_FAILURE'

export const ACCOUNT_GET_REQUEST = 'ACCOUNT_GET_REQUEST'
export const ACCOUNT_GET_SUCCESS = 'ACCOUNT_GET_SUCCESS'
export const ACCOUNT_GET_FAILURE = 'ACCOUNT_GET_FAILURE'

export const ADD_UPDATE_USER_ADDRESSES_REQUEST = 'ADD_UPDATE_USER_ADDRESSES_REQUEST'
export const ADD_UPDATE_USER_ADDRESSES_SUCCESS = 'ADD_UPDATE_USER_ADDRESSES_SUCCESS'
export const ADD_UPDATE_USER_ADDRESSES_FAILURE = 'ADD_UPDATE_USER_ADDRESSES_FAILURE'

export const QUESTION_GET_ALL_REQUEST = 'QUESTION_GET_ALL_REQUEST'
export const QUESTION_GET_ALL_SUCCESS = 'QUESTION_GET_ALL_SUCCESS'
export const QUESTION_GET_ALL_FAILURE = 'QUESTION_GET_ALL_FAILURE'

export const CREATE_QUESTION_REQUEST = 'CREATE_QUESTION_REQUEST'
export const CREATE_QUESTION_SUCCESS = 'CREATE_QUESTION_SUCCESS'
export const CREATE_QUESTION_FAILURE = 'CREATE_QUESTION_FAILURE'

export const UPDATE_QUESTION_REQUEST = 'UPDATE_QUESTION_REQUEST'
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_FAILURE = 'UPDATE_QUESTION_FAILURE'
