export const USER_GET_REQUEST = 'USER_GET_REQUEST'
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS'
export const USER_GET_FAILURE = 'USER_GET_FAILURE'

export const USERS_GET_REQUEST = 'USERS_GET_REQUEST'
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS'
export const USERS_GET_FAILURE = 'USERS_GET_FAILURE'

export const USER_PROFILE_GET_ALL_REQUEST = 'USER_PROFILE_GET_ALL_REQUEST'
export const USER_PROFILE_GET_ALL_SUCCESS = 'USER_PROFILE_GET_ALL_SUCCESS'
export const USER_PROFILE_GET_ALL_FAILURE = 'USER_PROFILE_GET_ALL_FAILURE'

export const ACCOUNT_GET_REQUEST = 'ACCOUNT_GET_REQUEST'
export const ACCOUNT_GET_SUCCESS = 'ACCOUNT_GET_SUCCESS'
export const ACCOUNT_GET_FAILURE = 'ACCOUNT_GET_FAILURE'

export const ADD_UPDATE_USER_ADDRESSES_REQUEST = 'ADD_UPDATE_USER_ADDRESSES_REQUEST'
export const ADD_UPDATE_USER_ADDRESSES_SUCCESS = 'ADD_UPDATE_USER_ADDRESSES_SUCCESS'
export const ADD_UPDATE_USER_ADDRESSES_FAILURE = 'ADD_UPDATE_USER_ADDRESSES_FAILURE'
