export const PROVINCE_GET_ALL_REQUEST = 'PROVINCE_GET_ALL_REQUEST'
export const PROVINCE_GET_ALL_SUCCESS = 'PROVINCE_GET_ALL_SUCCESS'
export const PROVINCE_GET_ALL_FAILURE = 'PROVINCE_GET_ALL_FAILURE'

export const PROVINCE_GET_REQUEST = 'PROVINCE_GET_REQUEST'
export const PROVINCE_GET_SUCCESS = 'PROVINCE_GET_SUCCESS'
export const PROVINCE_GET_FAILURE = 'PROVINCE_GET_FAILURE'

export const DISTRICT_GET_ALL_REQUEST = 'DISTRICT_GET_ALL_REQUEST'
export const DISTRICT_GET_ALL_SUCCESS = 'DISTRICT_GET_ALL_SUCCESS'
export const DISTRICT_GET_ALL_FAILURE = 'DISTRICT_GET_ALL_FAILURE'

export const DISTRICT_GET_REQUEST = 'DISTRICT_GET_REQUEST'
export const DISTRICT_GET_SUCCESS = 'DISTRICT_GET_SUCCESS'
export const DISTRICT_GET_FAILURE = 'DISTRICT_GET_FAILURE'

export const WARD_GET_ALL_REQUEST = 'WARD_GET_ALL_REQUEST'
export const WARD_GET_ALL_SUCCESS = 'WARD_GET_ALL_SUCCESS'
export const WARD_GET_ALL_FAILURE = 'WARD_GET_ALL_FAILURE'

export const UPDATE_QUARTER_TREE_REQUEST = 'UPDATE_QUARTER_TREE_REQUEST'
export const UPDATE_QUARTER_TREE_SUCCESS = 'UPDATE_QUARTER_TREE_SUCCESS'

export const HOTLINE_BY_WARD_GET_REQUEST = 'HOTLINE_BY_WARD_GET_REQUEST'
export const HOTLINE_BY_WARD_GET_SUCCESS = 'HOTLINE_BY_WARD_GET_SUCCESS'
export const HOTLINE_BY_WARD_GET_FAILURE = 'HOTLINE_BY_WARD_GET_FAILURE'
